### ISSUE TITLE
Block Crack

### ISSUE THREAD

**Issue by andrei923** [MrMicky-FR/FastParticles#1]
I'm trying to use block crack particle but is always invalid texture "the pink thing".
i've used 
`			FastParticle.spawnParticle(world, ParticleType.BLOCK_CRACK, loc, 1, Material.DIRT)
			FastParticle.spawnParticle(world, ParticleType.BLOCK_CRACK, loc, 0, 0, 0, 1, Material.DIRT)`

spigot 1.8.8

**Comment by MrMicky-FR** [comment]
The data type for `BLOCK_CRACK` is `MaterialData` and not `Material`, if you replace the data `Material.DIRT` with `new MaterialData(Material.DIRT)` it should work :)

**Comment by andrei923** [comment]
Thanks a lot, now works.
