### ISSUE TITLE
Spell mob color

### ISSUE THREAD

**Issue by LoneDev6** [MrMicky-FR/FastParticles#2]
Hello!
Amazing API, thanks for it.

Please can you add Colors to Spell mob particle? https://www.spigotmc.org/wiki/colored-particles/

https://github.com/MrMicky-FR/FastParticles/blob/f901235937cd976f11cd9fbeb34ad5cbc2f0f15a/src/main/java/fr/mrmicky/fastparticle/ParticleType.java

**Comment by SergejKembel** [comment]
Any progess?

**Comment by MrMicky-FR** [comment]
Sorry for the long delay, it could be a nice addition but I don't think it's in the scope of this library.

The goal of FastParticles is only to provide a compatibility bridge for plugins that need to be able to work with pre 1.9 servers (when there was no particle API in Bukkit). Therefore, new features will only be added if they are added in the Bukkit Particles API.

Also it's possible to spawn colored spell mobs particles, you just need to use the offsetX, offsetY and offsetZ properties.
