### ISSUE TITLE
Footstep particle

### ISSUE THREAD

**Issue by andrei923** [MrMicky-FR/FastParticles#4]
Hello, can you enable the footstep particle? thank you.

**Comment by MrMicky-FR** [comment]
Done in 2ceefe3c73e77e40db661afdd32d33ce3ada30ec and 7b1c4e1e7078634772fdff1948f5d9fbec4175fe, but this particle has been removed in Minecraft 1.13 so it can't be spawned on 1.13+ servers and will not be visible to 1.13+ players.
